### ISSUE TITLE
Change app version popup to footer indicator 

### ISSUE THREAD

**Issue by VictorWinberg** [VictorWinberg/qr-hunt#378]
**Is your feature request related to a problem? Please describe.**

It is annoying with the app updates popups.

**Describe the solution you'd like**

Instead indicate it in the footer with an icon or text format, that is clickable to see changes and auto-remove icon/text-format after 60s.

**Comment by AnnieLeonia** [comment]
Something like this:
<img width="299" alt="Screenshot 2022-07-05 at 08 59 32" src="https://user-images.githubusercontent.com/13522509/177268825-5f07f138-9ed5-4dc6-8b33-6adca31c72d5.png">
